export const readers = [
  {
    id: 'clr1reader001',
    lastName: 'Иванов',
    firstName: 'Александр',
    addressStreet: 'ул. Пушкина, 10',
    adressCity: 'Москва',
    phoneNumber: '+7(900)123-45-67',
    registratedDate: '2023-01-15',
    status: 'active',
    category: 'student',
  },
  {
    id: 'clr1reader002',
    lastName: 'Петрова',
    firstName: 'Екатерина',
    addressStreet: 'пр. Ленина, 25',
    adressCity: 'Санкт-Петербург',
    phoneNumber: '+7(911)234-56-78',
    registratedDate: '2023-02-03',
    status: 'active',
    category: 'teacher',
  },
  {
    id: 'clr1reader003',
    lastName: 'Сидоров',
    firstName: 'Иван',
    addressStreet: 'ул. Гагарина, 5',
    adressCity: 'Казань',
    phoneNumber: '+7(917)345-67-89',
    registratedDate: '2023-01-20',
    status: 'active',
    category: 'student',
  },
  {
    id: 'clr1reader004',
    lastName: 'Козлова',
    firstName: 'Мария',
    addressStreet: 'ул. Кирова, 15',
    adressCity: 'Новосибирск',
    phoneNumber: '+7(913)456-78-90',
    registratedDate: '2023-03-05',
    status: 'active',
    category: 'pensioner',
  },
  {
    id: 'clr1reader005',
    lastName: 'Смирнов',
    firstName: 'Дмитрий',
    addressStreet: 'ул. Советская, 8',
    adressCity: 'Екатеринбург',
    phoneNumber: '+7(922)567-89-01',
    registratedDate: '2023-02-10',
    status: 'active',
    category: 'worker',
  },
  {
    id: 'clr1reader006',
    lastName: 'Николаева',
    firstName: 'Анна',
    addressStreet: 'пр. Мира, 42',
    adressCity: 'Нижний Новгород',
    phoneNumber: '+7(930)678-90-12',
    registratedDate: '2023-01-25',
    status: 'inactive',
    category: 'student',
  },
  {
    id: 'clr1reader007',
    lastName: 'Кузнецов',
    firstName: 'Сергей',
    addressStreet: 'ул. Лесная, 3',
    adressCity: 'Самара',
    phoneNumber: '+7(927)789-01-23',
    registratedDate: '2023-03-15',
    status: 'active',
    category: 'worker',
  },
  {
    id: 'clr1reader008',
    lastName: 'Морозова',
    firstName: 'Ольга',
    addressStreet: 'ул. Центральная, 20',
    adressCity: 'Омск',
    phoneNumber: '+7(904)890-12-34',
    registratedDate: '2023-02-20',
    status: 'active',
    category: 'teacher',
  },
  {
    id: 'clr1reader009',
    lastName: 'Васильев',
    firstName: 'Андрей',
    addressStreet: 'пр. Победы, 55',
    adressCity: 'Челябинск',
    phoneNumber: '+7(951)901-23-45',
    registratedDate: '2023-01-30',
    status: 'active',
    category: 'student',
  },
  {
    id: 'clr1reader010',
    lastName: 'Федорова',
    firstName: 'Татьяна',
    addressStreet: 'ул. Набережная, 12',
    adressCity: 'Ростов-на-Дону',
    phoneNumber: '+7(918)012-34-56',
    registratedDate: '2023-03-25',
    status: 'active',
    category: 'pensioner',
  },
  {
    id: 'clr1reader011',
    lastName: 'Михайлов',
    firstName: 'Павел',
    addressStreet: 'ул. Школьная, 7',
    adressCity: 'Уфа',
    phoneNumber: '+7(937)123-45-67',
    registratedDate: '2023-02-05',
    status: 'active',
    category: 'worker',
  },
  {
    id: 'clr1reader012',
    lastName: 'Соколова',
    firstName: 'Наталья',
    addressStreet: 'пр. Гагарина, 30',
    adressCity: 'Красноярск',
    phoneNumber: '+7(923)234-56-78',
    registratedDate: '2023-01-12',
    status: 'inactive',
    category: 'teacher',
  },
  {
    id: 'clr1reader013',
    lastName: 'Новиков',
    firstName: 'Алексей',
    addressStreet: 'ул. Ленина, 18',
    adressCity: 'Воронеж',
    phoneNumber: '+7(920)345-67-89',
    registratedDate: '2023-03-08',
    status: 'active',
    category: 'student',
  },
  {
    id: 'clr1reader014',
    lastName: 'Волкова',
    firstName: 'Елена',
    addressStreet: 'ул. Садовая, 22',
    adressCity: 'Пермь',
    phoneNumber: '+7(912)456-78-90',
    registratedDate: '2023-02-15',
    status: 'active',
    category: 'worker',
  },
  {
    id: 'clr1reader015',
    lastName: 'Зайцев',
    firstName: 'Игорь',
    addressStreet: 'пр. Комсомольский, 40',
    adressCity: 'Волгоград',
    phoneNumber: '+7(927)567-89-01',
    registratedDate: '2023-01-22',
    status: 'active',
    category: 'pensioner',
  },
  {
    id: 'clr1reader016',
    lastName: 'Макарова',
    firstName: 'Светлана',
    addressStreet: 'ул. Молодежная, 5',
    adressCity: 'Саратов',
    phoneNumber: '+7(917)678-90-12',
    registratedDate: '2023-03-18',
    status: 'active',
    category: 'teacher',
  },
  {
    id: 'clr1reader017',
    lastName: 'Андреев',
    firstName: 'Виктор',
    addressStreet: 'ул. Парковая, 15',
    adressCity: 'Краснодар',
    phoneNumber: '+7(918)789-01-23',
    registratedDate: '2023-02-25',
    status: 'active',
    category: 'worker',
  },
  {
    id: 'clr1reader018',
    lastName: 'Степанова',
    firstName: 'Ирина',
    addressStreet: 'пр. Строителей, 28',
    adressCity: 'Тольятти',
    phoneNumber: '+7(927)890-12-34',
    registratedDate: '2023-01-18',
    status: 'inactive',
    category: 'student',
  },
  {
    id: 'clr1reader019',
    lastName: 'Яковлев',
    firstName: 'Николай',
    addressStreet: 'ул. Дружбы, 10',
    adressCity: 'Ижевск',
    phoneNumber: '+7(912)901-23-45',
    registratedDate: '2023-03-12',
    status: 'active',
    category: 'pensioner',
  },
  {
    id: 'clr1reader020',
    lastName: 'Сорокина',
    firstName: 'Юлия',
    addressStreet: 'ул. Солнечная, 7',
    adressCity: 'Барнаул',
    phoneNumber: '+7(913)012-34-56',
    registratedDate: '2023-02-08',
    status: 'active',
    category: 'teacher',
  },
  {
    id: 'clr1reader021',
    lastName: 'Романов',
    firstName: 'Евгений',
    addressStreet: 'пр. Октябрьский, 33',
    adressCity: 'Владивосток',
    phoneNumber: '+7(924)123-45-67',
    registratedDate: '2023-01-28',
    status: 'active',
    category: 'worker',
  },
  {
    id: 'clr1reader022',
    lastName: 'Захарова',
    firstName: 'Алина',
    addressStreet: 'ул. Весенняя, 19',
    adressCity: 'Ульяновск',
    phoneNumber: '+7(917)234-56-78',
    registratedDate: '2023-03-22',
    status: 'active',
    category: 'student',
  },
  {
    id: 'clr1reader023',
    lastName: 'Борисов',
    firstName: 'Максим',
    addressStreet: 'ул. Цветочная, 8',
    adressCity: 'Ярославль',
    phoneNumber: '+7(910)345-67-89',
    registratedDate: '2023-02-12',
    status: 'active',
    category: 'worker',
  },
  {
    id: 'clr1reader024',
    lastName: 'Королева',
    firstName: 'Дарья',
    addressStreet: 'пр. Космонавтов, 45',
    adressCity: 'Томск',
    phoneNumber: '+7(913)456-78-90',
    registratedDate: '2023-01-10',
    status: 'inactive',
    category: 'teacher',
  },
  {
    id: 'clr1reader025',
    lastName: 'Герасимов',
    firstName: 'Артем',
    addressStreet: 'ул. Зеленая, 12',
    adressCity: 'Оренбург',
    phoneNumber: '+7(922)567-89-01',
    registratedDate: '2023-03-02',
    status: 'active',
    category: 'student',
  },
  {
    id: 'clr1reader026',
    lastName: 'Кузьмина',
    firstName: 'Валерия',
    addressStreet: 'ул. Речная, 24',
    adressCity: 'Кемерово',
    phoneNumber: '+7(923)678-90-12',
    registratedDate: '2023-02-18',
    status: 'active',
    category: 'pensioner',
  },
  {
    id: 'clr1reader027',
    lastName: 'Ильин',
    firstName: 'Денис',
    addressStreet: 'пр. Металлургов, 37',
    adressCity: 'Новокузнецк',
    phoneNumber: '+7(923)789-01-23',
    registratedDate: '2023-01-05',
    status: 'active',
    category: 'worker',
  },
  {
    id: 'clr1reader028',
    lastName: 'Гусева',
    firstName: 'Ксения',
    addressStreet: 'ул. Спортивная, 9',
    adressCity: 'Рязань',
    phoneNumber: '+7(910)890-12-34',
    registratedDate: '2023-03-28',
    status: 'active',
    category: 'student',
  },
  {
    id: 'clr1reader029',
    lastName: 'Титов',
    firstName: 'Руслан',
    addressStreet: 'ул. Березовая, 14',
    adressCity: 'Астрахань',
    phoneNumber: '+7(917)901-23-45',
    registratedDate: '2023-02-22',
    status: 'active',
    category: 'teacher',
  },
  {
    id: 'clr1reader030',
    lastName: 'Никитина',
    firstName: 'Полина',
    addressStreet: 'пр. Энтузиастов, 50',
    adressCity: 'Набережные Челны',
    phoneNumber: '+7(927)012-34-56',
    registratedDate: '2023-01-15',
    status: 'inactive',
    category: 'student',
  },
  {
    id: 'clr1reader031',
    lastName: 'Марков',
    firstName: 'Кирилл',
    addressStreet: 'ул. Луговая, 6',
    adressCity: 'Пенза',
    phoneNumber: '+7(927)123-45-67',
    registratedDate: '2023-03-10',
    status: 'active',
    category: 'worker',
  },
  {
    id: 'clr1reader032',
    lastName: 'Антонова',
    firstName: 'Вероника',
    addressStreet: 'ул. Сосновая, 21',
    adressCity: 'Липецк',
    phoneNumber: '+7(904)234-56-78',
    registratedDate: '2023-02-02',
    status: 'active',
    category: 'pensioner',
  },
  {
    id: 'clr1reader033',
    lastName: 'Тарасов',
    firstName: 'Глеб',
    addressStreet: 'пр. Дзержинского, 32',
    adressCity: 'Тула',
    phoneNumber: '+7(910)345-67-89',
    registratedDate: '2023-01-25',
    status: 'active',
    category: 'student',
  },
  {
    id: 'clr1reader034',
    lastName: 'Лебедева',
    firstName: 'Софья',
    addressStreet: 'ул. Вишневая, 11',
    adressCity: 'Киров',
    phoneNumber: '+7(912)456-78-90',
    registratedDate: '2023-03-15',
    status: 'active',
    category: 'teacher',
  },
  {
    id: 'clr1reader035',
    lastName: 'Филиппов',
    firstName: 'Тимур',
    addressStreet: 'ул. Рабочая, 17',
    adressCity: 'Чебоксары',
    phoneNumber: '+7(917)567-89-01',
    registratedDate: '2023-02-28',
    status: 'active',
    category: 'worker',
  },
  {
    id: 'clr1reader036',
    lastName: 'Давыдова',
    firstName: 'Милана',
    addressStreet: 'пр. Московский, 60',
    adressCity: 'Калининград',
    phoneNumber: '+7(911)678-90-12',
    registratedDate: '2023-01-08',
    status: 'inactive',
    category: 'student',
  },
  {
    id: 'clr1reader037',
    lastName: 'Беляев',
    firstName: 'Роман',
    addressStreet: 'ул. Озерная, 13',
    adressCity: 'Курск',
    phoneNumber: '+7(910)789-01-23',
    registratedDate: '2023-03-05',
    status: 'active',
    category: 'pensioner',
  },
  {
    id: 'clr1reader038',
    lastName: 'Осипова',
    firstName: 'Виктория',
    addressStreet: 'ул. Полевая, 26',
    adressCity: 'Улан-Удэ',
    phoneNumber: '+7(924)890-12-34',
    registratedDate: '2023-02-15',
    status: 'active',
    category: 'teacher',
  },
  {
    id: 'clr1reader039',
    lastName: 'Комаров',
    firstName: 'Владислав',
    addressStreet: 'пр. Ленинградский, 38',
    adressCity: 'Ставрополь',
    phoneNumber: '+7(918)901-23-45',
    registratedDate: '2023-01-20',
    status: 'active',
    category: 'worker',
  },
  {
    id: 'clr1reader040',
    lastName: 'Панова',
    firstName: 'Алиса',
    addressStreet: 'ул. Кленовая, 4',
    adressCity: 'Сочи',
    phoneNumber: '+7(918)012-34-56',
    registratedDate: '2023-03-25',
    status: 'active',
    category: 'student',
  },
  {
    id: 'clr1reader041',
    lastName: 'Голубев',
    firstName: 'Станислав',
    addressStreet: 'ул. Тихая, 16',
    adressCity: 'Иваново',
    phoneNumber: '+7(910)123-45-67',
    registratedDate: '2023-02-10',
    status: 'active',
    category: 'worker',
  },
  {
    id: 'clr1reader042',
    lastName: 'Виноградова',
    firstName: 'Евгения',
    addressStreet: 'пр. Юбилейный, 27',
    adressCity: 'Брянск',
    phoneNumber: '+7(910)234-56-78',
    registratedDate: '2023-01-03',
    status: 'inactive',
    category: 'teacher',
  },
  {
    id: 'clr1reader043',
    lastName: 'Богданов',
    firstName: 'Даниил',
    addressStreet: 'ул. Дачная, 9',
    adressCity: 'Владимир',
    phoneNumber: '+7(904)345-67-89',
    registratedDate: '2023-03-20',
    status: 'active',
    category: 'student',
  },
  {
    id: 'clr1reader044',
    lastName: 'Воробьева',
    firstName: 'Арина',
    addressStreet: 'ул. Заводская, 23',
    adressCity: 'Белгород',
    phoneNumber: '+7(910)456-78-90',
    registratedDate: '2023-02-05',
    status: 'active',
    category: 'pensioner',
  },
  {
    id: 'clr1reader045',
    lastName: 'Киселев',
    firstName: 'Георгий',
    addressStreet: 'пр. Северный, 41',
    adressCity: 'Архангельск',
    phoneNumber: '+7(911)567-89-01',
    registratedDate: '2023-01-30',
    status: 'active',
    category: 'worker',
  },
  {
    id: 'clr1reader046',
    lastName: 'Ковалева',
    firstName: 'Василиса',
    addressStreet: 'ул. Южная, 18',
    adressCity: 'Калуга',
    phoneNumber: '+7(910)678-90-12',
    registratedDate: '2023-03-08',
    status: 'active',
    category: 'student',
  },
  {
    id: 'clr1reader047',
    lastName: 'Ефимов',
    firstName: 'Михаил',
    addressStreet: 'ул. Восточная, 29',
    adressCity: 'Смоленск',
    phoneNumber: '+7(910)789-01-23',
    registratedDate: '2023-02-20',
    status: 'active',
    category: 'teacher',
  },
  {
    id: 'clr1reader048',
    lastName: 'Мельникова',
    firstName: 'Кристина',
    addressStreet: 'пр. Западный, 36',
    adressCity: 'Курган',
    phoneNumber: '+7(912)890-12-34',
    registratedDate: '2023-01-12',
    status: 'inactive',
    category: 'student',
  },
  {
    id: 'clr1reader049',
    lastName: 'Щербаков',
    firstName: 'Антон',
    addressStreet: 'ул. Северная, 14',
    adressCity: 'Орел',
    phoneNumber: '+7(910)901-23-45',
    registratedDate: '2023-03-30',
    status: 'active',
    category: 'worker',
  },
  {
    id: 'clr1reader050',
    lastName: 'Блинова',
    firstName: 'Маргарита',
    addressStreet: 'ул. Западная, 22',
    adressCity: 'Мурманск',
    phoneNumber: '+7(911)012-34-56',
    registratedDate: '2023-02-25',
    status: 'active',
    category: 'pensioner',
  },
];

export const extraditions = [
  {
    id: 'clr1extradition001',
    extraditionDate: '2023-04-01',
    refundDate: '2023-04-15',
    readerId: 'clr1reader001',
  },
  {
    id: 'clr1extradition002',
    extraditionDate: '2023-04-02',
    refundDate: '2023-04-16',
    readerId: 'clr1reader002',
  },
  {
    id: 'clr1extradition003',
    extraditionDate: '2023-04-03',
    refundDate: '2023-04-17',
    readerId: 'clr1reader003',
  },
  {
    id: 'clr1extradition004',
    extraditionDate: '2023-04-04',
    refundDate: '2023-04-18',
    readerId: 'clr1reader004',
  },
  {
    id: 'clr1extradition005',
    extraditionDate: '2023-04-05',
    refundDate: '2023-04-19',
    readerId: 'clr1reader005',
  },
  {
    id: 'clr1extradition006',
    extraditionDate: '2023-04-06',
    refundDate: '2023-04-20',
    readerId: 'clr1reader006',
  },
  {
    id: 'clr1extradition007',
    extraditionDate: '2023-04-07',
    refundDate: '2023-04-21',
    readerId: 'clr1reader007',
  },
  {
    id: 'clr1extradition008',
    extraditionDate: '2023-04-08',
    refundDate: '2023-04-22',
    readerId: 'clr1reader008',
  },
  {
    id: 'clr1extradition009',
    extraditionDate: '2023-04-09',
    refundDate: '2023-04-23',
    readerId: 'clr1reader009',
  },
  {
    id: 'clr1extradition010',
    extraditionDate: '2023-04-10',
    refundDate: '2023-04-24',
    readerId: 'clr1reader010',
  },
  {
    id: 'clr1extradition011',
    extraditionDate: '2023-04-11',
    refundDate: '2023-04-25',
    readerId: 'clr1reader011',
  },
  {
    id: 'clr1extradition012',
    extraditionDate: '2023-04-12',
    refundDate: '2023-04-26',
    readerId: 'clr1reader012',
  },
  {
    id: 'clr1extradition013',
    extraditionDate: '2023-04-13',
    refundDate: '2023-04-27',
    readerId: 'clr1reader013',
  },
  {
    id: 'clr1extradition014',
    extraditionDate: '2023-04-14',
    refundDate: '2023-04-28',
    readerId: 'clr1reader014',
  },
  {
    id: 'clr1extradition015',
    extraditionDate: '2023-04-15',
    refundDate: '2023-04-29',
    readerId: 'clr1reader015',
  },
  {
    id: 'clr1extradition016',
    extraditionDate: '2023-04-16',
    refundDate: '2023-04-30',
    readerId: 'clr1reader016',
  },
  {
    id: 'clr1extradition017',
    extraditionDate: '2023-04-17',
    refundDate: '2023-05-01',
    readerId: 'clr1reader017',
  },
  {
    id: 'clr1extradition018',
    extraditionDate: '2023-04-18',
    refundDate: '2023-05-02',
    readerId: 'clr1reader018',
  },
  {
    id: 'clr1extradition019',
    extraditionDate: '2023-04-19',
    refundDate: '2023-05-03',
    readerId: 'clr1reader019',
  },
  {
    id: 'clr1extradition020',
    extraditionDate: '2023-04-20',
    refundDate: '2023-05-04',
    readerId: 'clr1reader020',
  },
  {
    id: 'clr1extradition021',
    extraditionDate: '2023-04-21',
    refundDate: '2023-05-05',
    readerId: 'clr1reader021',
  },
  {
    id: 'clr1extradition022',
    extraditionDate: '2023-04-22',
    refundDate: '2023-05-06',
    readerId: 'clr1reader022',
  },
  {
    id: 'clr1extradition023',
    extraditionDate: '2023-04-23',
    refundDate: '2023-05-07',
    readerId: 'clr1reader023',
  },
  {
    id: 'clr1extradition024',
    extraditionDate: '2023-04-24',
    refundDate: '2023-05-08',
    readerId: 'clr1reader024',
  },
  {
    id: 'clr1extradition025',
    extraditionDate: '2023-04-25',
    refundDate: '2023-05-09',
    readerId: 'clr1reader025',
  },
  {
    id: 'clr1extradition026',
    extraditionDate: '2023-04-26',
    refundDate: null,
    readerId: 'clr1reader026',
  },
  {
    id: 'clr1extradition027',
    extraditionDate: '2023-04-27',
    refundDate: null,
    readerId: 'clr1reader027',
  },
  {
    id: 'clr1extradition028',
    extraditionDate: '2023-04-28',
    refundDate: null,
    readerId: 'clr1reader028',
  },
  {
    id: 'clr1extradition029',
    extraditionDate: '2023-04-29',
    refundDate: null,
    readerId: 'clr1reader029',
  },
  {
    id: 'clr1extradition030',
    extraditionDate: '2023-04-30',
    refundDate: null,
    readerId: 'clr1reader030',
  },
  {
    id: 'clr1extradition031',
    extraditionDate: '2023-05-01',
    refundDate: null,
    readerId: 'clr1reader031',
  },
  {
    id: 'clr1extradition032',
    extraditionDate: '2023-05-02',
    refundDate: null,
    readerId: 'clr1reader032',
  },
  {
    id: 'clr1extradition033',
    extraditionDate: '2023-05-03',
    refundDate: null,
    readerId: 'clr1reader033',
  },
  {
    id: 'clr1extradition034',
    extraditionDate: '2023-05-04',
    refundDate: null,
    readerId: 'clr1reader034',
  },
  {
    id: 'clr1extradition035',
    extraditionDate: '2023-05-05',
    refundDate: null,
    readerId: 'clr1reader035',
  },
  {
    id: 'clr1extradition036',
    extraditionDate: '2023-05-06',
    refundDate: null,
    readerId: 'clr1reader036',
  },
  {
    id: 'clr1extradition037',
    extraditionDate: '2023-05-07',
    refundDate: null,
    readerId: 'clr1reader037',
  },
  {
    id: 'clr1extradition038',
    extraditionDate: '2023-05-08',
    refundDate: null,
    readerId: 'clr1reader038',
  },
  {
    id: 'clr1extradition039',
    extraditionDate: '2023-05-09',
    refundDate: null,
    readerId: 'clr1reader039',
  },
  {
    id: 'clr1extradition040',
    extraditionDate: '2023-05-10',
    refundDate: null,
    readerId: 'clr1reader040',
  },
  {
    id: 'clr1extradition041',
    extraditionDate: '2023-05-11',
    refundDate: null,
    readerId: 'clr1reader041',
  },
  {
    id: 'clr1extradition042',
    extraditionDate: '2023-05-12',
    refundDate: null,
    readerId: 'clr1reader042',
  },
  {
    id: 'clr1extradition043',
    extraditionDate: '2023-05-13',
    refundDate: null,
    readerId: 'clr1reader043',
  },
  {
    id: 'clr1extradition044',
    extraditionDate: '2023-05-14',
    refundDate: null,
    readerId: 'clr1reader044',
  },
  {
    id: 'clr1extradition045',
    extraditionDate: '2023-05-15',
    refundDate: null,
    readerId: 'clr1reader045',
  },
  {
    id: 'clr1extradition046',
    extraditionDate: '2023-05-16',
    refundDate: null,
    readerId: 'clr1reader046',
  },
  {
    id: 'clr1extradition047',
    extraditionDate: '2023-05-17',
    refundDate: null,
    readerId: 'clr1reader047',
  },
  {
    id: 'clr1extradition048',
    extraditionDate: '2023-05-18',
    refundDate: null,
    readerId: 'clr1reader048',
  },
  {
    id: 'clr1extradition049',
    extraditionDate: '2023-05-19',
    refundDate: null,
    readerId: 'clr1reader049',
  },
  {
    id: 'clr1extradition050',
    extraditionDate: '2023-05-20',
    refundDate: null,
    readerId: 'clr1reader050',
  },
];

export const debts = [
  {
    id: 'clr1debt001',
    date: '2023-04-22',
    extraditionId: 'clr1extradition001',
  },
  {
    id: 'clr1debt002',
    date: '2023-04-23',
    extraditionId: 'clr1extradition002',
  },
  {
    id: 'clr1debt003',
    date: '2023-04-24',
    extraditionId: 'clr1extradition003',
  },
  {
    id: 'clr1debt004',
    date: '2023-04-25',
    extraditionId: 'clr1extradition004',
  },
  {
    id: 'clr1debt005',
    date: '2023-04-26',
    extraditionId: 'clr1extradition005',
  },
  {
    id: 'clr1debt006',
    date: '2023-04-27',
    extraditionId: 'clr1extradition006',
  },
  {
    id: 'clr1debt007',
    date: '2023-04-28',
    extraditionId: 'clr1extradition007',
  },
  {
    id: 'clr1debt008',
    date: '2023-04-29',
    extraditionId: 'clr1extradition008',
  },
  {
    id: 'clr1debt009',
    date: '2023-04-30',
    extraditionId: 'clr1extradition009',
  },
  {
    id: 'clr1debt010',
    date: '2023-05-01',
    extraditionId: 'clr1extradition010',
  },
  {
    id: 'clr1debt011',
    date: '2023-05-02',
    extraditionId: 'clr1extradition011',
  },
  {
    id: 'clr1debt012',
    date: '2023-05-03',
    extraditionId: 'clr1extradition012',
  },
  {
    id: 'clr1debt013',
    date: '2023-05-04',
    extraditionId: 'clr1extradition013',
  },
  {
    id: 'clr1debt014',
    date: '2023-05-05',
    extraditionId: 'clr1extradition014',
  },
  {
    id: 'clr1debt015',
    date: '2023-05-06',
    extraditionId: 'clr1extradition015',
  },
  {
    id: 'clr1debt016',
    date: '2023-05-07',
    extraditionId: 'clr1extradition016',
  },
  {
    id: 'clr1debt017',
    date: '2023-05-08',
    extraditionId: 'clr1extradition017',
  },
  {
    id: 'clr1debt018',
    date: '2023-05-09',
    extraditionId: 'clr1extradition018',
  },
  {
    id: 'clr1debt019',
    date: '2023-05-10',
    extraditionId: 'clr1extradition019',
  },
  {
    id: 'clr1debt020',
    date: '2023-05-11',
    extraditionId: 'clr1extradition020',
  },
  {
    id: 'clr1debt021',
    date: '2023-05-12',
    extraditionId: 'clr1extradition021',
  },
  {
    id: 'clr1debt022',
    date: '2023-05-13',
    extraditionId: 'clr1extradition022',
  },
  {
    id: 'clr1debt023',
    date: '2023-05-14',
    extraditionId: 'clr1extradition023',
  },
  {
    id: 'clr1debt024',
    date: '2023-05-15',
    extraditionId: 'clr1extradition024',
  },
  {
    id: 'clr1debt025',
    date: '2023-05-16',
    extraditionId: 'clr1extradition025',
  },
  {
    id: 'clr1debt026',
    date: '2023-05-17',
    extraditionId: 'clr1extradition026',
  },
  {
    id: 'clr1debt027',
    date: '2023-05-18',
    extraditionId: 'clr1extradition027',
  },
  {
    id: 'clr1debt028',
    date: '2023-05-19',
    extraditionId: 'clr1extradition028',
  },
  {
    id: 'clr1debt029',
    date: '2023-05-20',
    extraditionId: 'clr1extradition029',
  },
  {
    id: 'clr1debt030',
    date: '2023-05-21',
    extraditionId: 'clr1extradition030',
  },
  {
    id: 'clr1debt031',
    date: '2023-05-22',
    extraditionId: 'clr1extradition031',
  },
  {
    id: 'clr1debt032',
    date: '2023-05-23',
    extraditionId: 'clr1extradition032',
  },
  {
    id: 'clr1debt033',
    date: '2023-05-24',
    extraditionId: 'clr1extradition033',
  },
  {
    id: 'clr1debt034',
    date: '2023-05-25',
    extraditionId: 'clr1extradition034',
  },
  {
    id: 'clr1debt035',
    date: '2023-05-26',
    extraditionId: 'clr1extradition035',
  },
  {
    id: 'clr1debt036',
    date: '2023-05-27',
    extraditionId: 'clr1extradition036',
  },
  {
    id: 'clr1debt037',
    date: '2023-05-28',
    extraditionId: 'clr1extradition037',
  },
  {
    id: 'clr1debt038',
    date: '2023-05-29',
    extraditionId: 'clr1extradition038',
  },
  {
    id: 'clr1debt039',
    date: '2023-05-30',
    extraditionId: 'clr1extradition039',
  },
  {
    id: 'clr1debt040',
    date: '2023-05-31',
    extraditionId: 'clr1extradition040',
  },
  {
    id: 'clr1debt041',
    date: '2023-06-01',
    extraditionId: 'clr1extradition041',
  },
  {
    id: 'clr1debt042',
    date: '2023-06-02',
    extraditionId: 'clr1extradition042',
  },
  {
    id: 'clr1debt043',
    date: '2023-06-03',
    extraditionId: 'clr1extradition043',
  },
  {
    id: 'clr1debt044',
    date: '2023-06-04',
    extraditionId: 'clr1extradition044',
  },
  {
    id: 'clr1debt045',
    date: '2023-06-05',
    extraditionId: 'clr1extradition045',
  },
  {
    id: 'clr1debt046',
    date: '2023-06-06',
    extraditionId: 'clr1extradition046',
  },
  {
    id: 'clr1debt047',
    date: '2023-06-07',
    extraditionId: 'clr1extradition047',
  },
  {
    id: 'clr1debt048',
    date: '2023-06-08',
    extraditionId: 'clr1extradition048',
  },
  {
    id: 'clr1debt049',
    date: '2023-06-09',
    extraditionId: 'clr1extradition049',
  },
  {
    id: 'clr1debt050',
    date: '2023-06-10',
    extraditionId: 'clr1extradition050',
  },
];

export const bookBaseData = [
  {
    name: 'Улисс',
    trackingNumber: 10101,
    publicationCount: 2000,
    publisher: 'Эксмо',
    publishedYear: 2015,
    pagesCount: 928,
    genere: 'Модернизм',
  },
  {
    name: 'Божественная комедия',
    trackingNumber: 10102,
    publicationCount: 3500,
    publisher: 'АСТ',
    publishedYear: 2016,
    pagesCount: 864,
    genere: 'Классическая литература',
  },
  {
    name: 'Дон Кихот',
    trackingNumber: 10103,
    publicationCount: 4000,
    publisher: 'Азбука',
    publishedYear: 2017,
    pagesCount: 1056,
    genere: 'Классическая литература',
  },
  {
    name: 'Гамлет',
    trackingNumber: 10104,
    publicationCount: 3000,
    publisher: 'Эксмо',
    publishedYear: 2018,
    pagesCount: 384,
    genere: 'Драма',
  },
  {
    name: 'Илиада',
    trackingNumber: 10105,
    publicationCount: 2500,
    publisher: 'АСТ',
    publishedYear: 2019,
    pagesCount: 576,
    genere: 'Эпос',
  },
  {
    name: 'Одиссея',
    trackingNumber: 10106,
    publicationCount: 2500,
    publisher: 'Азбука',
    publishedYear: 2015,
    pagesCount: 544,
    genere: 'Эпос',
  },
  {
    name: 'Фауст',
    trackingNumber: 10107,
    publicationCount: 2000,
    publisher: 'Эксмо',
    publishedYear: 2016,
    pagesCount: 480,
    genere: 'Классическая литература',
  },
  {
    name: 'Гордость и предубеждение',
    trackingNumber: 10108,
    publicationCount: 3500,
    publisher: 'АСТ',
    publishedYear: 2017,
    pagesCount: 416,
    genere: 'Роман',
  },
  {
    name: 'Джейн Эйр',
    trackingNumber: 10109,
    publicationCount: 3000,
    publisher: 'Азбука',
    publishedYear: 2018,
    pagesCount: 608,
    genere: 'Роман',
  },
  {
    name: 'Грозовой перевал',
    trackingNumber: 10110,
    publicationCount: 2500,
    publisher: 'Эксмо',
    publishedYear: 2019,
    pagesCount: 384,
    genere: 'Готический роман',
  },
  {
    name: 'Моби Дик',
    trackingNumber: 10111,
    publicationCount: 2000,
    publisher: 'АСТ',
    publishedYear: 2015,
    pagesCount: 704,
    genere: 'Приключения',
  },
  {
    name: 'Над пропастью во ржи',
    trackingNumber: 10112,
    publicationCount: 4000,
    publisher: 'Азбука',
    publishedYear: 2016,
    pagesCount: 288,
    genere: 'Роман',
  },
  {
    name: 'Великий Гэтсби',
    trackingNumber: 10113,
    publicationCount: 3500,
    publisher: 'Эксмо',
    publishedYear: 2017,
    pagesCount: 256,
    genere: 'Роман',
  },
  {
    name: 'Унесенные ветром',
    trackingNumber: 10114,
    publicationCount: 3000,
    publisher: 'АСТ',
    publishedYear: 2018,
    pagesCount: 1088,
    genere: 'Исторический роман',
  },
  {
    name: 'Лолита',
    trackingNumber: 10115,
    publicationCount: 2500,
    publisher: 'Азбука',
    publishedYear: 2019,
    pagesCount: 448,
    genere: 'Роман',
  },
  {
    name: 'Сто лет одиночества',
    trackingNumber: 10116,
    publicationCount: 4000,
    publisher: 'Эксмо',
    publishedYear: 2015,
    pagesCount: 416,
    genere: 'Магический реализм',
  },
  {
    name: 'Повелитель мух',
    trackingNumber: 10117,
    publicationCount: 3000,
    publisher: 'АСТ',
    publishedYear: 2016,
    pagesCount: 256,
    genere: 'Роман',
  },
  {
    name: '1984',
    trackingNumber: 10118,
    publicationCount: 5000,
    publisher: 'Азбука',
    publishedYear: 2017,
    pagesCount: 320,
    genere: 'Антиутопия',
  },
  {
    name: 'О дивный новый мир',
    trackingNumber: 10119,
    publicationCount: 3500,
    publisher: 'Эксмо',
    publishedYear: 2018,
    pagesCount: 288,
    genere: 'Антиутопия',
  },
  {
    name: 'Скотный двор',
    trackingNumber: 10120,
    publicationCount: 3000,
    publisher: 'АСТ',
    publishedYear: 2019,
    pagesCount: 128,
    genere: 'Сатира',
  },
  {
    name: 'Портрет Дориана Грея',
    trackingNumber: 10121,
    publicationCount: 2500,
    publisher: 'Азбука',
    publishedYear: 2015,
    pagesCount: 320,
    genere: 'Готический роман',
  },
  {
    name: 'Франкенштейн',
    trackingNumber: 10122,
    publicationCount: 2000,
    publisher: 'Эксмо',
    publishedYear: 2016,
    pagesCount: 288,
    genere: 'Готический роман',
  },
  {
    name: 'Дракула',
    trackingNumber: 10123,
    publicationCount: 3000,
    publisher: 'АСТ',
    publishedYear: 2017,
    pagesCount: 480,
    genere: 'Готический роман',
  },
  {
    name: 'Приключения Тома Сойера',
    trackingNumber: 10124,
    publicationCount: 4000,
    publisher: 'Азбука',
    publishedYear: 2018,
    pagesCount: 288,
    genere: 'Приключения',
  },
  {
    name: 'Приключения Гекльберри Финна',
    trackingNumber: 10125,
    publicationCount: 3500,
    publisher: 'Эксмо',
    publishedYear: 2019,
    pagesCount: 384,
    genere: 'Приключения',
  },
  {
    name: 'Робинзон Крузо',
    trackingNumber: 10126,
    publicationCount: 3000,
    publisher: 'АСТ',
    publishedYear: 2015,
    pagesCount: 320,
    genere: 'Приключения',
  },
  {
    name: 'Остров сокровищ',
    trackingNumber: 10127,
    publicationCount: 3500,
    publisher: 'Азбука',
    publishedYear: 2016,
    pagesCount: 288,
    genere: 'Приключения',
  },
  {
    name: 'Алиса в стране чудес',
    trackingNumber: 10128,
    publicationCount: 5000,
    publisher: 'Эксмо',
    publishedYear: 2017,
    pagesCount: 192,
    genere: 'Сказка',
  },
  {
    name: 'Алиса в Зазеркалье',
    trackingNumber: 10129,
    publicationCount: 4000,
    publisher: 'АСТ',
    publishedYear: 2018,
    pagesCount: 224,
    genere: 'Сказка',
  },
  {
    name: 'Винни-Пух',
    trackingNumber: 10130,
    publicationCount: 6000,
    publisher: 'Азбука',
    publishedYear: 2019,
    pagesCount: 160,
    genere: 'Детская литература',
  },
  {
    name: 'Хоббит',
    trackingNumber: 10131,
    publicationCount: 5000,
    publisher: 'Эксмо',
    publishedYear: 2015,
    pagesCount: 384,
    genere: 'Фэнтези',
  },
  {
    name: 'Гарри Поттер и Тайная комната',
    trackingNumber: 10132,
    publicationCount: 10000,
    publisher: 'Росмэн',
    publishedYear: 2016,
    pagesCount: 480,
    genere: 'Фэнтези',
  },
  {
    name: 'Гарри Поттер и узник Азкабана',
    trackingNumber: 10133,
    publicationCount: 10000,
    publisher: 'Росмэн',
    publishedYear: 2017,
    pagesCount: 528,
    genere: 'Фэнтези',
  },
  {
    name: 'Гарри Поттер и Кубок огня',
    trackingNumber: 10134,
    publicationCount: 9000,
    publisher: 'Росмэн',
    publishedYear: 2018,
    pagesCount: 704,
    genere: 'Фэнтези',
  },
  {
    name: 'Гарри Поттер и Орден Феникса',
    trackingNumber: 10135,
    publicationCount: 8000,
    publisher: 'Росмэн',
    publishedYear: 2019,
    pagesCount: 896,
    genere: 'Фэнтези',
  },
  {
    name: 'Гарри Поттер и Принц-полукровка',
    trackingNumber: 10136,
    publicationCount: 8000,
    publisher: 'Росмэн',
    publishedYear: 2015,
    pagesCount: 672,
    genere: 'Фэнтези',
  },
  {
    name: 'Гарри Поттер и Дары Смерти',
    trackingNumber: 10137,
    publicationCount: 9000,
    publisher: 'Росмэн',
    publishedYear: 2016,
    pagesCount: 704,
    genere: 'Фэнтези',
  },
  {
    name: 'Игра престолов',
    trackingNumber: 10138,
    publicationCount: 7000,
    publisher: 'АСТ',
    publishedYear: 2017,
    pagesCount: 768,
    genere: 'Фэнтези',
  },
  {
    name: 'Битва королей',
    trackingNumber: 10139,
    publicationCount: 6000,
    publisher: 'АСТ',
    publishedYear: 2018,
    pagesCount: 896,
    genere: 'Фэнтези',
  },
  {
    name: 'Буря мечей',
    trackingNumber: 10140,
    publicationCount: 6000,
    publisher: 'АСТ',
    publishedYear: 2019,
    pagesCount: 1184,
    genere: 'Фэнтези',
  },
  {
    name: 'Пир стервятников',
    trackingNumber: 10141,
    publicationCount: 5000,
    publisher: 'АСТ',
    publishedYear: 2015,
    pagesCount: 768,
    genere: 'Фэнтези',
  },
  {
    name: 'Танец с драконами',
    trackingNumber: 10142,
    publicationCount: 5500,
    publisher: 'АСТ',
    publishedYear: 2016,
    pagesCount: 1152,
    genere: 'Фэнтези',
  },
  {
    name: 'Властелин Колец: Братство Кольца',
    trackingNumber: 10143,
    publicationCount: 7000,
    publisher: 'АСТ',
    publishedYear: 2017,
    pagesCount: 576,
    genere: 'Фэнтези',
  },
  {
    name: 'Властелин Колец: Две крепости',
    trackingNumber: 10144,
    publicationCount: 6500,
    publisher: 'АСТ',
    publishedYear: 2018,
    pagesCount: 512,
    genere: 'Фэнтези',
  },
  {
    name: 'Властелин Колец: Возвращение короля',
    trackingNumber: 10145,
    publicationCount: 6500,
    publisher: 'АСТ',
    publishedYear: 2019,
    pagesCount: 512,
    genere: 'Фэнтези',
  },
  {
    name: 'Сильмариллион',
    trackingNumber: 10146,
    publicationCount: 4000,
    publisher: 'АСТ',
    publishedYear: 2015,
    pagesCount: 432,
    genere: 'Фэнтези',
  },
  {
    name: 'Дюна',
    trackingNumber: 10147,
    publicationCount: 5000,
    publisher: 'АСТ',
    publishedYear: 2016,
    pagesCount: 704,
    genere: 'Научная фантастика',
  },
  {
    name: 'Мессия Дюны',
    trackingNumber: 10148,
    publicationCount: 4000,
    publisher: 'АСТ',
    publishedYear: 2017,
    pagesCount: 320,
    genere: 'Научная фантастика',
  },
  {
    name: 'Дети Дюны',
    trackingNumber: 10149,
    publicationCount: 4000,
    publisher: 'АСТ',
    publishedYear: 2018,
    pagesCount: 480,
    genere: 'Научная фантастика',
  },
  {
    name: 'Бог-Император Дюны',
    trackingNumber: 10150,
    publicationCount: 3500,
    publisher: 'АСТ',
    publishedYear: 2019,
    pagesCount: 608,
    genere: 'Научная фантастика',
  },
  {
    name: 'Еретики Дюны',
    trackingNumber: 10151,
    publicationCount: 3500,
    publisher: 'АСТ',
    publishedYear: 2015,
    pagesCount: 640,
    genere: 'Научная фантастика',
  },
  {
    name: 'Капитул Дюны',
    trackingNumber: 10152,
    publicationCount: 3000,
    publisher: 'АСТ',
    publishedYear: 2016,
    pagesCount: 608,
    genere: 'Научная фантастика',
  },
  {
    name: 'Основание',
    trackingNumber: 10153,
    publicationCount: 4500,
    publisher: 'Эксмо',
    publishedYear: 2017,
    pagesCount: 384,
    genere: 'Научная фантастика',
  },
  {
    name: 'Основание и Империя',
    trackingNumber: 10154,
    publicationCount: 4000,
    publisher: 'Эксмо',
    publishedYear: 2018,
    pagesCount: 384,
    genere: 'Научная фантастика',
  },
  {
    name: 'Второе основание',
    trackingNumber: 10155,
    publicationCount: 4000,
    publisher: 'Эксмо',
    publishedYear: 2019,
    pagesCount: 384,
    genere: 'Научная фантастика',
  },
  {
    name: 'Край основания',
    trackingNumber: 10156,
    publicationCount: 3500,
    publisher: 'Эксмо',
    publishedYear: 2015,
    pagesCount: 416,
    genere: 'Научная фантастика',
  },
  {
    name: 'Основание и Земля',
    trackingNumber: 10157,
    publicationCount: 3500,
    publisher: 'Эксмо',
    publishedYear: 2016,
    pagesCount: 448,
    genere: 'Научная фантастика',
  },
  {
    name: 'Я, робот',
    trackingNumber: 10158,
    publicationCount: 5000,
    publisher: 'Эксмо',
    publishedYear: 2017,
    pagesCount: 320,
    genere: 'Научная фантастика',
  },
  {
    name: 'Конец вечности',
    trackingNumber: 10159,
    publicationCount: 3000,
    publisher: 'Эксмо',
    publishedYear: 2018,
    pagesCount: 352,
    genere: 'Научная фантастика',
  },
  {
    name: 'Сами боги',
    trackingNumber: 10160,
    publicationCount: 3000,
    publisher: 'Эксмо',
    publishedYear: 2019,
    pagesCount: 384,
    genere: 'Научная фантастика',
  },
  {
    name: 'Солярис',
    trackingNumber: 10161,
    publicationCount: 4000,
    publisher: 'АСТ',
    publishedYear: 2015,
    pagesCount: 288,
    genere: 'Научная фантастика',
  },
  {
    name: 'Звездный дневник Ийона Тихого',
    trackingNumber: 10162,
    publicationCount: 3000,
    publisher: 'АСТ',
    publishedYear: 2016,
    pagesCount: 416,
    genere: 'Научная фантастика',
  },
  {
    name: 'Кибериада',
    trackingNumber: 10163,
    publicationCount: 2500,
    publisher: 'АСТ',
    publishedYear: 2017,
    pagesCount: 480,
    genere: 'Научная фантастика',
  },
  {
    name: 'Непобедимый',
    trackingNumber: 10164,
    publicationCount: 2500,
    publisher: 'АСТ',
    publishedYear: 2018,
    pagesCount: 288,
    genere: 'Научная фантастика',
  },
  {
    name: 'Футурологический конгресс',
    trackingNumber: 10165,
    publicationCount: 2000,
    publisher: 'АСТ',
    publishedYear: 2019,
    pagesCount: 224,
    genere: 'Научная фантастика',
  },
  {
    name: 'Автостопом по галактике',
    trackingNumber: 10166,
    publicationCount: 6000,
    publisher: 'АСТ',
    publishedYear: 2015,
    pagesCount: 224,
    genere: 'Научная фантастика',
  },
  {
    name: 'Ресторан в конце Вселенной',
    trackingNumber: 10167,
    publicationCount: 5000,
    publisher: 'АСТ',
    publishedYear: 2016,
    pagesCount: 224,
    genere: 'Научная фантастика',
  },
  {
    name: 'Жизнь, Вселенная и всё остальное',
    trackingNumber: 10168,
    publicationCount: 5000,
    publisher: 'АСТ',
    publishedYear: 2017,
    pagesCount: 224,
    genere: 'Научная фантастика',
  },
  {
    name: 'В основном безвредна',
    trackingNumber: 10169,
    publicationCount: 4000,
    publisher: 'АСТ',
    publishedYear: 2018,
    pagesCount: 224,
    genere: 'Научная фантастика',
  },
  {
    name: 'И ещё кое-что...',
    trackingNumber: 10170,
    publicationCount: 4000,
    publisher: 'АСТ',
    publishedYear: 2019,
    pagesCount: 256,
    genere: 'Научная фантастика',
  },
  {
    name: 'Нейромант',
    trackingNumber: 10171,
    publicationCount: 4500,
    publisher: 'АСТ',
    publishedYear: 2015,
    pagesCount: 384,
    genere: 'Киберпанк',
  },
  {
    name: 'Граф Ноль',
    trackingNumber: 10172,
    publicationCount: 3500,
    publisher: 'АСТ',
    publishedYear: 2016,
    pagesCount: 352,
    genere: 'Киберпанк',
  },
  {
    name: 'Мона Лиза овердрайв',
    trackingNumber: 10173,
    publicationCount: 3500,
    publisher: 'АСТ',
    publishedYear: 2017,
    pagesCount: 384,
    genere: 'Киберпанк',
  },
  {
    name: 'Снежный крах',
    trackingNumber: 10174,
    publicationCount: 4000,
    publisher: 'АСТ',
    publishedYear: 2018,
    pagesCount: 480,
    genere: 'Киберпанк',
  },
  {
    name: 'Алмазный век',
    trackingNumber: 10175,
    publicationCount: 3500,
    publisher: 'АСТ',
    publishedYear: 2019,
    pagesCount: 512,
    genere: 'Киберпанк',
  },
  {
    name: 'Криптономикон',
    trackingNumber: 10176,
    publicationCount: 3000,
    publisher: 'АСТ',
    publishedYear: 2015,
    pagesCount: 912,
    genere: 'Технотриллер',
  },
  {
    name: 'Анафем',
    trackingNumber: 10177,
    publicationCount: 2500,
    publisher: 'АСТ',
    publishedYear: 2016,
    pagesCount: 864,
    genere: 'Научная фантастика',
  },
  {
    name: 'Семиевие',
    trackingNumber: 10178,
    publicationCount: 2500,
    publisher: 'АСТ',
    publishedYear: 2017,
    pagesCount: 960,
    genere: 'Научная фантастика',
  },
  {
    name: 'Марсианин',
    trackingNumber: 10179,
    publicationCount: 6000,
    publisher: 'АСТ',
    publishedYear: 2018,
    pagesCount: 384,
    genere: 'Научная фантастика',
  },
  {
    name: 'Артемида',
    trackingNumber: 10180,
    publicationCount: 5000,
    publisher: 'АСТ',
    publishedYear: 2019,
    pagesCount: 384,
    genere: 'Научная фантастика',
  },
  {
    name: 'Проект «Аве Мария»',
    trackingNumber: 10181,
    publicationCount: 5000,
    publisher: 'АСТ',
    publishedYear: 2015,
    pagesCount: 608,
    genere: 'Научная фантастика',
  },
  {
    name: 'Интерстеллар',
    trackingNumber: 10182,
    publicationCount: 5500,
    publisher: 'АСТ',
    publishedYear: 2016,
    pagesCount: 352,
    genere: 'Научная фантастика',
  },
  {
    name: 'Контакт',
    trackingNumber: 10183,
    publicationCount: 4000,
    publisher: 'АСТ',
    publishedYear: 2017,
    pagesCount: 416,
    genere: 'Научная фантастика',
  },
  {
    name: 'Космическая одиссея 2001 года',
    trackingNumber: 10184,
    publicationCount: 4500,
    publisher: 'АСТ',
    publishedYear: 2018,
    pagesCount: 288,
    genere: 'Научная фантастика',
  },
  {
    name: 'Космическая одиссея 2010 года',
    trackingNumber: 10185,
    publicationCount: 4000,
    publisher: 'АСТ',
    publishedYear: 2019,
    pagesCount: 320,
    genere: 'Научная фантастика',
  },
  {
    name: 'Космическая одиссея 2061 года',
    trackingNumber: 10186,
    publicationCount: 3500,
    publisher: 'АСТ',
    publishedYear: 2015,
    pagesCount: 288,
    genere: 'Научная фантастика',
  },
  {
    name: 'Космическая одиссея 3001 года',
    trackingNumber: 10187,
    publicationCount: 3500,
    publisher: 'АСТ',
    publishedYear: 2016,
    pagesCount: 288,
    genere: 'Научная фантастика',
  },
  {
    name: 'Пикник на обочине',
    trackingNumber: 10188,
    publicationCount: 5000,
    publisher: 'АСТ',
    publishedYear: 2017,
    pagesCount: 256,
    genere: 'Научная фантастика',
  },
  {
    name: 'Трудно быть богом',
    trackingNumber: 10189,
    publicationCount: 5500,
    publisher: 'АСТ',
    publishedYear: 2018,
    pagesCount: 224,
    genere: 'Научная фантастика',
  },
  {
    name: 'Понедельник начинается в субботу',
    trackingNumber: 10190,
    publicationCount: 6000,
    publisher: 'АСТ',
    publishedYear: 2019,
    pagesCount: 320,
    genere: 'Научная фантастика',
  },
  {
    name: 'Обитаемый остров',
    trackingNumber: 10191,
    publicationCount: 4500,
    publisher: 'АСТ',
    publishedYear: 2015,
    pagesCount: 416,
    genere: 'Научная фантастика',
  },
  {
    name: 'Жук в муравейнике',
    trackingNumber: 10192,
    publicationCount: 4000,
    publisher: 'АСТ',
    publishedYear: 2016,
    pagesCount: 352,
    genere: 'Научная фантастика',
  },
  {
    name: 'Волны гасят ветер',
    trackingNumber: 10193,
    publicationCount: 3500,
    publisher: 'АСТ',
    publishedYear: 2017,
    pagesCount: 320,
    genere: 'Научная фантастика',
  },
  {
    name: 'Метро 2034',
    trackingNumber: 10194,
    publicationCount: 6000,
    publisher: 'АСТ',
    publishedYear: 2018,
    pagesCount: 384,
    genere: 'Постапокалиптика',
  },
  {
    name: 'Метро 2035',
    trackingNumber: 10195,
    publicationCount: 6000,
    publisher: 'АСТ',
    publishedYear: 2019,
    pagesCount: 384,
    genere: 'Постапокалиптика',
  },
  {
    name: 'Будущее',
    trackingNumber: 10196,
    publicationCount: 4000,
    publisher: 'АСТ',
    publishedYear: 2015,
    pagesCount: 480,
    genere: 'Антиутопия',
  },
  {
    name: 'Текст',
    trackingNumber: 10197,
    publicationCount: 5000,
    publisher: 'АСТ',
    publishedYear: 2016,
    pagesCount: 320,
    genere: 'Современная проза',
  },
  {
    name: 'Сумерки',
    trackingNumber: 10198,
    publicationCount: 7000,
    publisher: 'АСТ',
    publishedYear: 2017,
    pagesCount: 448,
    genere: 'Фэнтези',
  },
  {
    name: 'Новолуние',
    trackingNumber: 10199,
    publicationCount: 6500,
    publisher: 'АСТ',
    publishedYear: 2018,
    pagesCount: 544,
    genere: 'Фэнтези',
  },
  {
    name: 'Затмение',
    trackingNumber: 10200,
    publicationCount: 6500,
    publisher: 'АСТ',
    publishedYear: 2019,
    pagesCount: 636,
    genere: 'Фэнтези',
  },
  // Добавляем еще 20 новых книг
  {
    name: 'Рассвет',
    trackingNumber: 10201,
    publicationCount: 6000,
    publisher: 'АСТ',
    publishedYear: 2015,
    pagesCount: 612,
    genere: 'Фэнтези',
  },
  {
    name: 'Солнце полуночи',
    trackingNumber: 10202,
    publicationCount: 7000,
    publisher: 'АСТ',
    publishedYear: 2016,
    pagesCount: 754,
    genere: 'Фэнтези',
  },
  {
    name: 'Голодные игры',
    trackingNumber: 10203,
    publicationCount: 8000,
    publisher: 'АСТ',
    publishedYear: 2017,
    pagesCount: 384,
    genere: 'Антиутопия',
  },
  {
    name: 'И вспыхнет пламя',
    trackingNumber: 10204,
    publicationCount: 7500,
    publisher: 'АСТ',
    publishedYear: 2018,
    pagesCount: 416,
    genere: 'Антиутопия',
  },
  {
    name: 'Сойка-пересмешница',
    trackingNumber: 10205,
    publicationCount: 7500,
    publisher: 'АСТ',
    publishedYear: 2019,
    pagesCount: 448,
    genere: 'Антиутопия',
  },
  {
    name: 'Бегущий в лабиринте',
    trackingNumber: 10206,
    publicationCount: 6000,
    publisher: 'АСТ',
    publishedYear: 2015,
    pagesCount: 448,
    genere: 'Антиутопия',
  },
  {
    name: 'Испытание огнем',
    trackingNumber: 10207,
    publicationCount: 5500,
    publisher: 'АСТ',
    publishedYear: 2016,
    pagesCount: 416,
    genere: 'Антиутопия',
  },
  {
    name: 'Лекарство от смерти',
    trackingNumber: 10208,
    publicationCount: 5500,
    publisher: 'АСТ',
    publishedYear: 2017,
    pagesCount: 384,
    genere: 'Антиутопия',
  },
  {
    name: 'Дивергент',
    trackingNumber: 10209,
    publicationCount: 7000,
    publisher: 'Эксмо',
    publishedYear: 2018,
    pagesCount: 416,
    genere: 'Антиутопия',
  },
  {
    name: 'Инсургент',
    trackingNumber: 10210,
    publicationCount: 6500,
    publisher: 'Эксмо',
    publishedYear: 2019,
    pagesCount: 448,
    genere: 'Антиутопия',
  },
  {
    name: 'Эллигент',
    trackingNumber: 10211,
    publicationCount: 6500,
    publisher: 'Эксмо',
    publishedYear: 2015,
    pagesCount: 480,
    genere: 'Антиутопия',
  },
  {
    name: 'Четыре',
    trackingNumber: 10212,
    publicationCount: 5000,
    publisher: 'Эксмо',
    publishedYear: 2016,
    pagesCount: 352,
    genere: 'Антиутопия',
  },
  {
    name: 'Пятая волна',
    trackingNumber: 10213,
    publicationCount: 5500,
    publisher: 'Эксмо',
    publishedYear: 2017,
    pagesCount: 480,
    genere: 'Научная фантастика',
  },
  {
    name: 'Бесконечное море',
    trackingNumber: 10214,
    publicationCount: 5000,
    publisher: 'Эксмо',
    publishedYear: 2018,
    pagesCount: 416,
    genere: 'Научная фантастика',
  },
  {
    name: 'Последняя звезда',
    trackingNumber: 10215,
    publicationCount: 5000,
    publisher: 'Эксмо',
    publishedYear: 2019,
    pagesCount: 384,
    genere: 'Научная фантастика',
  },
  {
    name: 'Гордость и предубеждение и зомби',
    trackingNumber: 10216,
    publicationCount: 4500,
    publisher: 'Эксмо',
    publishedYear: 2015,
    pagesCount: 384,
    genere: 'Мэшап',
  },
  {
    name: 'Разум и чувства и гады морские',
    trackingNumber: 10217,
    publicationCount: 4000,
    publisher: 'Эксмо',
    publishedYear: 2016,
    pagesCount: 352,
    genere: 'Мэшап',
  },
  {
    name: 'Андроид Каренина',
    trackingNumber: 10218,
    publicationCount: 4000,
    publisher: 'Эксмо',
    publishedYear: 2017,
    pagesCount: 512,
    genere: 'Мэшап',
  },
  {
    name: 'Авраам Линкольн: Охотник на вампиров',
    trackingNumber: 10219,
    publicationCount: 5000,
    publisher: 'Эксмо',
    publishedYear: 2018,
    pagesCount: 384,
    genere: 'Мэшап',
  },
  {
    name: 'Дневники вампира',
    trackingNumber: 10220,
    publicationCount: 6000,
    publisher: 'Эксмо',
    publishedYear: 2019,
    pagesCount: 448,
    genere: 'Фэнтези',
  },
];

// Создаем книги с привязкой к выдачам
const books = [];
// Распределяем 30 книг по 50 выдачам
for (let i = 0; i < extraditions.length; i++) {
  const extraditionId = `clr1extradition${(i + 1).toString().padStart(3, '0')}`;
  const bookIndex = i % bookBaseData.length; // Используем книги по кругу

  // Копируем базовые данные книги
  const bookData = { ...bookBaseData[bookIndex] };

  // Добавляем связь с выдачей
  bookData.extraditionId = extraditionId;

  // Добавляем книгу в массив
  books.push(bookData);
}

// Функция для очистки данных перед загрузкой
async function cleanupDatabase(prisma) {
  console.log('Очистка базы данных перед загрузкой seed-данных...');

  // Очищаем таблицы в правильном порядке с учетом зависимостей
  // Сначала удаляем записи из таблиц, которые ссылаются на другие таблицы
  await prisma.debt.deleteMany({});

  // Удаляем записи из таблицы книг
  await prisma.book.deleteMany({});

  // Удаляем записи из таблицы выдач
  await prisma.extradition.deleteMany({});

  // Удаляем записи из таблицы читателей
  await prisma.reader.deleteMany({});

  console.log('База данных очищена.');
}

// Функция для создания seed-данных
async function main(prisma) {
  // Очищаем базу данных перед загрузкой новых данных
  await cleanupDatabase(prisma);

  console.log('Начало загрузки seed-данных...');

  // Создаем читателей
  console.log('Создание читателей...');
  await prisma.reader.createMany({
    data: readers,
  });

  // Создаем выдачи
  console.log('Создание выдач...');
  await prisma.extradition.createMany({
    data: extraditions,
  });

  // Создаем книги с уже установленными связями с выдачами
  console.log('Создание книг с привязкой к выдачам...');
  await prisma.book.createMany({
    data: books,
  });

  // Создаем долги
  console.log('Создание долгов...');
  await prisma.debt.createMany({
    data: debts,
  });

  console.log('Загрузка seed-данных завершена успешно.');
}

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

main(prisma)
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
